In [1]:
import numpy as np

In [2]:
list_ = ['1', '2', '3', '4','5']
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
#Q1
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


yes there is a difference between list_ and array_list. list_ is a python "list" and array_list is a numpy array

In [8]:
#Q2
print("data type of elements in list_")
for i in list_:
    print(type(i))

data type of elements in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
print("data type of elements in araay_list")
for i in array_list:
    print(type(array_list))

data type of elements in araay_list
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
#Q3
array_list = np.array(object = list_ , dtype= int)

In [10]:
print("data type of array_list")
for i in array_list:
    print(type(i))

data type of array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
print("data type of elements in list_")
for i in list_:
    print(type(i))

data type of elements in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


yes there is difference in the data type of array_list and list_

In [12]:
import numpy as np

In [13]:
num_list = [ [1,2,3], [4,5,6] ]

In [14]:
num_array = np.array(object = num_list)

In [15]:
#Q4
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#(i)
np.shape(num_array)

(2, 3)

In [18]:
#(ii)
np.size(num_array)

6

In [19]:
#Q5
a = np.zeros((3,3))

In [20]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#Q6
b = np.eye(5)

In [27]:
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])